FROM scratch
MAINTAINER Aleksandar Diklic <rastasheep@gmail.com>

ADD ca-certificates.crt /etc/ssl/certs/

ADD packaging/api/root/usr/local/bin/utisak-api /api
ADD main/api/config/config.json /config.json

EXPOSE 8080

CMD ["/api", "--config=config.json"]
